-- 0003 realtime and storage

-- Realtime: alerts to the teacher dashboard and waiting room status.
alter publication supabase_realtime add table public.alerts;
alter publication supabase_realtime add table public.session_participants;

-- Private buckets. Uploads and downloads use signed URLs generated by the API (service role).
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('evidences', 'evidences', false, 2097152, array['image/jpeg', 'image/png', 'image/webp']),
  ('audio-segments', 'audio-segments', false, 5242880, array['audio/webm', 'audio/wav', 'audio/ogg', 'audio/mpeg']),
  ('reference-faces', 'reference-faces', false, 2097152, array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do nothing;
